const districtNames = [
    "Buenas Bananas",
    "Tobacco Trees",
    "Apricot Alley",
    "The Soils",
    "Sandy Secrets",
    "Lemon Lands",
    "Avocado Avenues",
    "Elon Estates",
    "Berrington Bay",
    "San Sapphire",
    "Tangerine Tinies",
    "Terrestial Town",
    "Grapey Gardens",
    "Buttergonia",
    "Port Pumpkin",
    "Lazy Lavenders",
    "Emerald Ends",
    "Starry Skies",
    "Basil Borough",
    "Mount Mango",
    "Muddy Mountains",
    "Froggy Forest",
    "Violet Ville",
    "Carrot Cove",
    "Wasted Woods",
    "Orbital Oasis",
    "Oyster Oceans",
    "Sunny Sands"]

export default districtNames;