const traitsData = [{"city":"Yellow Yards","district":"Buenas Bananas","street":"Gorilla Gate","special":""},
{"city":"Beige Bay","district":"Tobacco Trees","street":"Winston Way","special":""},
{"city":"Orange Oasis","district":"Apricot Alley","street":"Licky Loops","special":""},
{"city":"Beige Bay","district":"The Soils","street":"Rusty Ridge","special":""},
{"city":"Beige Bay","district":"Sandy Secrets","street":"Cobra Cove","special":""},
{"city":"Beige Bay","district":"Tobacco Trees","street":"Morris Mews","special":""},
{"city":"Yellow Yards","district":"Lemon Lands","street":"Peaky Parkway","special":""},
{"city":"Green Grove","district":"Avocado Avenues","street":"Smooth Suburbs","special":""},
{"city":"Yellow Yards","district":"Buenas Bananas","street":"Ape Gang Avenue","special":""},
{"city":"X AE X-II","district":"Elon Estates","street":"Ecliptic Ends","special":""},
{"city":"Purple Palms ","district":"Berrington Bay","street":"Raspberry Road","special":""},
{"city":"Blue Bayside","district":"San Sapphire","street":"Polished Plaza","special":""},
{"city":"Orange Oasis","district":"Tangerine Tinies","street":"Tiny Community","special":""},
{"city":"X AE X-II","district":"Terrestial Town","street":"Volcanic Ville","special":""},
{"city":"Purple Palms ","district":"Grapey Gardens","street":"Shiraz Square","special":""},
{"city":"Yellow Yards","district":"Buttergonia","street":"Cake Crescent","special":""},
{"city":"Orange Oasis","district":"Apricot Alley","street":"Fresh Rise","special":""},
{"city":"Purple Palms ","district":"Berrington Bay","street":"Blueberry Beach","special":""},
{"city":"Orange Oasis","district":"Port Pumpkin","street":"Scary Road","special":""},
{"city":"Blue Bayside","district":"San Sapphire","street":"Refractive Road","special":""},
{"city":"Beige Bay","district":"Tobacco Trees","street":"Lucky Lane","special":""},
{"city":"Purple Palms ","district":"Lazy Lavenders","street":"Scented Street","special":""},
{"city":"Green Grove","district":"Emerald Ends","street":"Resonance Road","special":""},
{"city":"Orange Oasis","district":"Tangerine Tinies","street":"Little Lane","special":""},
{"city":"Blue Bayside","district":"Starry Skies","street":"Galactic Gates","special":""},
{"city":"Purple Palms ","district":"Grapey Gardens","street":"Wine Way","special":""},
{"city":"Green Grove","district":"Basil Borough","street":"Pesto Park","special":""},
{"city":"Orange Oasis","district":"Mount Mango","street":"Juice Road","special":""},
{"city":"Beige Bay","district":"The Soils","street":"Pigeon Park","special":""},
{"city":"Beige Bay","district":"Muddy Mountains","street":"Clay Circus","special":""},
{"city":"Beige Bay","district":"The Soils","street":"Seed Street","special":""},
{"city":"Green Grove","district":"Froggy Forest","street":"Root Road","special":""},
{"city":"Purple Palms ","district":"Violet Ville","street":"Lobelia Lane","special":""},
{"city":"Yellow Yards","district":"Lemon Lands","street":"Squeezy Street","special":""},
{"city":"X AE X-II","district":"Elon Estates","street":"Rocket Ridge","special":""},
{"city":"Orange Oasis","district":"Carrot Cove","street":"Jumpy Lane","special":""},
{"city":"","district":"","street":"","special":"Candy Castle"},
{"city":"Beige Bay","district":"Wasted Woods","street":"Leaf Lane","special":""},
{"city":"Green Grove","district":"Froggy Forest","street":"Wasabi Way","special":""},
{"city":"Purple Palms ","district":"Berrington Bay","street":"Strawberry Square","special":""},
{"city":"Green Grove","district":"Emerald Ends","street":"Hammer Hill","special":""},
{"city":"X AE X-II","district":"Orbital Oasis","street":"Carmine Circus","special":""},
{"city":"Blue Bayside","district":"Starry Skies","street":"Hubble Hills","special":""},
{"city":"Yellow Yards","district":"Buttergonia","street":"Flour Way","special":""},
{"city":"Orange Oasis","district":"Mount Mango","street":"Naranja Narrows","special":""},
{"city":"Blue Bayside","district":"Oyster Oceans","street":"Salty Strip","special":""},
{"city":"Orange Oasis","district":"Carrot Cove","street":"Bunny Beach","special":""},
{"city":"Beige Bay","district":"Muddy Mountains","street":"Rough Road","special":""},
{"city":"Green Grove","district":"Froggy Forest","street":"Spicy Stream","special":""},
{"city":"Orange Oasis","district":"Carrot Cove","street":"Eyesight Road","special":""},
{"city":"X AE X-II","district":"Orbital Oasis","street":"Ruby Rise","special":""},
{"city":"Purple Palms ","district":"Grapey Gardens","street":"Raisin Road","special":""},
{"city":"Orange Oasis","district":"Mount Mango","street":"Pit Park","special":""},
{"city":"Yellow Yards","district":"Buttergonia","street":"Dough Drive","special":""},
{"city":"Beige Bay","district":"Wasted Woods","street":"Lumber Lake","special":""},
{"city":"","district":"","street":"","special":"Casa Blanca"},
{"city":"Green Grove","district":"Avocado Avenues","street":"Pagua Path","special":""},
{"city":"Beige Bay","district":"Sandy Secrets","street":"Dynamic Dunes","special":""},
{"city":"Orange Oasis","district":"Port Pumpkin","street":"Carved Lane","special":""},
{"city":"X AE X-II","district":"Terrestial Town","street":"Levitating Lavas","special":""},
{"city":"Orange Oasis","district":"Port Pumpkin","street":"Trick Or Street","special":""},
{"city":"Green Grove","district":"Avocado Avenues","street":"Guaca Gardens","special":""},
{"city":"X AE X-II","district":"Elon Estates","street":"Musky Alley","special":""},
{"city":"Beige Bay","district":"Sandy Secrets","street":"Gutter Gate","special":""},
{"city":"","district":"","street":"","special":"Cathedral of Wisdom"},
{"city":"X AE X-II","district":"Terrestial Town","street":"Ares Alpines","special":""},
{"city":"Beige Bay","district":"Muddy Mountains","street":"Wanderers Way","special":""},
{"city":"Beige Bay","district":"Wasted Woods","street":"Icy Isle","special":""},
{"city":"Yellow Yards","district":"Sunny Sands","street":"Shiny Street","special":""},
{"city":"Blue Bayside","district":"Starry Skies","street":"Beam Boulevard","special":""},
{"city":"Purple Palms ","district":"Violet Ville","street":"Amethyst Avenue","special":""},
{"city":"","district":"","street":"","special":"The Guardian"},
{"city":"X AE X-II","district":"Orbital Oasis","street":"Rover Road","special":""},
{"city":"Orange Oasis","district":"Apricot Alley","street":"Drippy Drive","special":""},
{"city":"Blue Bayside","district":"San Sapphire","street":"Hexagon Hills","special":""},
{"city":"Yellow Yards","district":"Lemon Lands","street":"Citrus Circus","special":""},
{"city":"Yellow Yards","district":"Sunny Sands","street":"Goldmann Lane","special":""},
{"city":"Blue Bayside","district":"Oyster Oceans","street":"Divers Drive","special":""},
{"city":"Yellow Yards","district":"Sunny Sands","street":"Sunray Road","special":""},
{"city":"Green Grove","district":"Basil Borough","street":"Fort Wenty","special":""},
{"city":"Blue Bayside","district":"Oyster Oceans","street":"Wavy Way","special":""},
{"city":"Purple Palms ","district":"Violet Ville","street":"Cider Crescent","special":""},
{"city":"Yellow Yards","district":"Buenas Bananas","street":"Kongs Cross","special":""},
{"city":"Purple Palms ","district":"Lazy Lavenders","street":"Fragrant Farm","special":""},
{"city":"Orange Oasis","district":"Tangerine Tinies","street":"Dreamy Drive","special":""},
{"city":"Purple Palms ","district":"Lazy Lavenders","street":"Mauve Meadow","special":""},
{"city":"Green Grove","district":"Basil Borough","street":"Dried Drive","special":""},
{"city":"Green Grove","district":"Emerald Ends","street":"Pine Path","special":""},
{"city":"","district":"","street":"","special":"The Money Pool"},
{"city":"","district":"","street":"","special":"Peter's Great Wall"},
{"city":"","district":"","street":"","special":"Spiky Singers"},
{"city":"","district":"","street":"","special":"Mystical Rocks"},
{"city":"","district":"","street":"","special":"The Impossible Bridge"},
{"city":"","district":"","street":"","special":"Palace of Eternity"},
{"city":"","district":"","street":"","special":"Property's Stadium"},
{"city":"","district":"","street":"","special":"The Secret Glass Pyramid"},
{"city":"","district":"","street":"","special":"Fort in the Leaves"},
{"city":"","district":"","street":"","special":"Mount Proper"},
{"city":"","district":"","street":"","special":"The Emperors Arena"},
{"city":"","district":"","street":"","special":"Le Tower"},
{"city":"","district":"","street":"","special":"Great Temple of Peter"},
{"city":"","district":"","street":"","special":"The Sunken City"},
{"city":"","district":"","street":"","special":"Ancient Labyrinth"},
{"city":"","district":"","street":"","special":"Question Cat"}]

export default traitsData;